-- MySQL Script generated by MySQL Workbench
-- Thu Jan 22 20:41:34 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myfolio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `myfolio` ;

-- -----------------------------------------------------
-- Table `myfolio`.`TEMPLATE_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfolio`.`TEMPLATE_TB` (
  `TEMPLATE_ID` INT NOT NULL AUTO_INCREMENT,
  `TEMPLATE_TITLE` VARCHAR(50) NOT NULL,
  `TEMPLATE_OWNER_USER_ID` VARCHAR(20) NULL,
  `TEMPLATE_DESCRIPTION` VARCHAR(200) NULL,
  PRIMARY KEY (`TEMPLATE_ID`),
  UNIQUE INDEX `TEMPLATE_ID_UNIQUE` (`TEMPLATE_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myfolio`.`PORTFOLIO_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfolio`.`PORTFOLIO_TB` (
  `PORTFOLIO_ID` INT NOT NULL AUTO_INCREMENT,
  `PORTFOLIO_TITLE` VARCHAR(50) NOT NULL,
  `PORTFOLIO_CONTENT_TAG` MEDIUMTEXT NOT NULL,
  `TEMPLATE_ID` INT NOT NULL,
  PRIMARY KEY (`PORTFOLIO_ID`),
  UNIQUE INDEX `PORTFOLIO_ID_UNIQUE` (`PORTFOLIO_ID` ASC),
  INDEX `fk_PORTFOLIO_TB_TEMPLATE_TB1_idx` (`TEMPLATE_ID` ASC),
  CONSTRAINT `fk_PORTFOLIO_TB_TEMPLATE_TB1`
    FOREIGN KEY (`TEMPLATE_ID`)
    REFERENCES `myfolio`.`TEMPLATE_TB` (`TEMPLATE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myfolio`.`USER_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfolio`.`USER_TB` (
  `USER_ID` VARCHAR(20) NOT NULL,
  `USER_NAME` VARCHAR(45) NULL,
  `USER_PW` VARCHAR(45) NOT NULL,
  `USER_CREATE_TIME` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PORTFOLIO_ID` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  INDEX `fk_USER_TB_PORTFOLIO_TB1_idx` (`PORTFOLIO_ID` ASC),
  CONSTRAINT `fk_USER_TB_PORTFOLIO_TB1`
    FOREIGN KEY (`PORTFOLIO_ID`)
    REFERENCES `myfolio`.`PORTFOLIO_TB` (`PORTFOLIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
