CREATE TABLE `myfolio`.`Portfolio_TB` (
  `USER_ID` VARCHAR(20) NOT NULL,
  `TEMPLATE_ID` VARCHAR(45) NOT NULL,
  `PORTFOLIO_TITLE` VARCHAR(50) NOT NULL,
  `PORTFOLIO_CONTENT_TAG` MEDIUMTEXT NOT NULL);
