CREATE TABLE `myfolio`.`Template_TB` (
  `ID` VARCHAR(20) NOT NULL,
  `TITLE` VARCHAR(50) NOT NULL,
  `OWNER_ID` VARCHAR(20) NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));
