CREATE TABLE `myfolio`.`Template_TB` (
  `TEMPLATE_ID` VARCHAR(20) NOT NULL,
  `TEMPLATE_TITLE` VARCHAR(50) NOT NULL,
  `TEMPLATE_OWNER_ID` VARCHAR(20) NULL,
  `TEMPLATE_DESCRIPTION` VARCHAR(200) NULL,
  PRIMARY KEY (`TEMPLATE_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`TEMPLATE_ID` ASC));
