CREATE TABLE `myfolio`.`User_TB` (
  `ID` VARCHAR(20) NOT NULL,
  `NAME` VARCHAR(20) NULL,
  `PW` VARCHAR(128) NOT NULL,
  `CREATE_TIME` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));